### ISSUE TITLE
Pinned ボタンの位置を右下に変更したい

### ISSUE THREAD

**Issue by usagizmo** [tinp-lab/Mokuren-feedback#10]
## 提案・要望
[Pinned] ボタンの位置を右下に変更したい。

## 背景
画面左下でなく右下についていたほうが、開いたり閉じたりがしやすいです。

**Comment by imajoriri** [comment]
@usagizmo 

要望ありがとうございます！
設定から左・右を選択できるようにする機能など解決策を考えております！

もしよろしければ参考までに、右下の方が押しやすい理由とかってあったりしますでしょうか??
(左下はすでに他のボタンがある、なんとなく右の方がぱっとする等なんでもかまいません！)

よろしくお願いいたします！

**Comment by usagizmo** [comment]
@imajoriri 

ありがとうございます！

> 右下の方が押しやすい理由とかってあったりしますでしょうか??

[Pinned] パネルの開閉時にマウスの移動距離が短くなるためです。

1. Pinned パネルを閉じるためには、マウスを画面右下に移動させる必要があります
2. 次に開くときに [Pinned] ボタンが右下にあれば、マウスの移動距離が短くなります

![CleanShot 2021-09-07 at 20 05 40](https://user-images.githubusercontent.com/1271863/132335441-49a6da40-1ac9-42e8-a0fe-98b1d144233a.png)

**Comment by imajoriri** [comment]
@usagizmo 

ご回答ありがとうございます！
なるほど、マウスボタンとの距離は盲点でした。

設定画面からの位置を変更できる機能を追加していこうと思います。
近日中にリリースできると思いますので、またこちらのIssueで報告させていただければと思います！

**Comment by imajoriri** [comment]
@usagizmo 

先ほどリリースされたversion1.2.0で、設定画面から左か右かを選択できる項目を追加しましたので、
ぜひお試しください！

![Issues_·_tinp-lab_issue-detail-sidebar_🔊](https://user-images.githubusercontent.com/30540418/132428153-9393c559-2af4-47e7-9937-ade69fb8672b.png)


---

chrome拡張の更新は `chrome://extensions/` こちらのデベロッパーモードをオンにして「更新」ボタンを押したら更新されます

**Comment by usagizmo** [comment]
@imajoriri 
迅速にありがとうございます！
更新も無事できました🎉

早速使わせていただきます！
