### ISSUE TITLE
pull requestもサイドバーに表示できるようにしてほしい

### ISSUE THREAD

**Issue by mochi-sann** [tinp-lab/Mokuren-feedback#11]
## 提案・要望

pull requestもissueの画面と同様にサイドバーに表示できるようにしてほしいです。

**Comment by imajoriri** [comment]
@mochi-sann 
Issueありがとうございます！
もしよかったら、

* ピンしたPRに対して使いたいのか、PR一覧で使えるようにしたいのか
* どのようなタイミングでそのように感じますか?

を教えていただけると幸いです！
機能検討の参考にさせていただければと思っておりますので、どうぞよろしくお願いします🙇‍♂️
