### ISSUE TITLE
Cancel Button Typo

### ISSUE THREAD

**Issue by mallowigi** [tinp-lab/Mokuren-feedback#13]
### Bug details
The cancel button when editing is mistyped

### App version
1.2.6

![CleanShot 2022-01-02 at 15 03 13](https://user-images.githubusercontent.com/5015756/147876663-60dd38a5-d455-4de7-94b2-9ad7d3d801b0.png)

**Comment by imajoriri** [comment]
@mallowigi 
Thank you!
I'll fix it right away.

**Comment by imajoriri** [comment]
@mallowigi

It's fixed in the latest version!
Thank you.
