### ISSUE TITLE
Projects→Add Cardsをした時の挙動がおかしい

### ISSUE THREAD

**Issue by UchinoHiroki1998** [tinp-lab/Mokuren-feedback#14]
### バグの内容

ProjectsからAdd Cardsをしたときに、本来はAdd Cardsのタブが画面右に表示されるはずなのに画面全体に表示されてしまいます。
修正よろしくお願いいたします。

### バージョン
2.0.1

**Comment by imajoriri** [comment]
@Uchino-recurrent 
バグの報告ありがとうございます！
こちらで再現できました。すぐに修正し、リリースしますのでしばらくお待ちください！

**Comment by UchinoHiroki1998** [comment]
@imajoriri 

ありがとうございます！
よろしくお願いします。
（Mokuren、非常に使いやすくて素晴らしいと思っています。開発していただきありがとうございます）

**Comment by imajoriri** [comment]
只今ストア申請中ですので、もうしばらくお待ちください！

**Comment by UchinoHiroki1998** [comment]
@imajoriri 

ありがとうございます！

**Comment by imajoriri** [comment]
@Uchino-recurrent 
休日にすいません！でも、いち早くお知らせしたく！

version2.0.4でこちらのバグを修正しました。
お手隙で確認してみてください！

確認して修正されていそうでしたらこちらのIssueをCloseしちゃってください！

### Mokurenのアップデート方法

chrome拡張は自動で更新されますが、すぐにアップデートするには拡張一覧ページから

1. デベロッパーモードON
2. 更新

で可能です！
**他のchrome拡張も更新されてしまうことに注意してください！**

<img width="1435" alt="スクリーンショット_2022-06-26_18_27_34" src="https://user-images.githubusercontent.com/30540418/175808080-ac071110-827f-44e8-b9a9-2ce34b91bebf.png">

**Comment by UchinoHiroki1998** [comment]
@imajoriri 

ありがとうございます！確認しました。非常に助かります！これからも使わせていただきます〜
