### ISSUE TITLE
表示しているサイドバーをショートカットで閉じられるようになると嬉しい

### ISSUE THREAD

**Issue by UchinoHiroki1998** [tinp-lab/Mokuren-feedback#15]
## 提案・要望
掲題の通りです。VSCode風にするならcommand + bとか...?

## 背景
右上の閉じるボタンを押さないと閉じられないのが少し面倒。
全ての操作をキーボードでしたいマンなのでよろしくお願いします。

**Comment by imajoriri** [comment]
@Uchino-recurrent 

ご要望ありがとうございます！
ショートカット、わかります！開発陣でも欲しいなと話しておりました。。

ぜひ、前向きに検討させていただきます！

**Comment by UchinoHiroki1998** [comment]
@imajoriri 

ありがとうございます、よろしくお願いします！
楽しみにしています！

**Comment by imajoriri** [comment]
@Uchino-recurrent 

お待たせしました！
こちら、最新のバージョン2.0.5で追加されました！

コマンド`⌘ + B`(windowsならCtrl+B)です。
ただ、こちら、Issueのコメント入力時の**Bold機能**とかぶってしまっているため、対策中です、すいません！

また、このコマンドが気に入らなければご自身でも変更可能ですのでぜひ試してみてください！

`chrome://extensions/shortcuts`こちらのパスをURLに打ち込んでいただければショートカット変更画面が開けます！

**Comment by UchinoHiroki1998** [comment]
@imajoriri 

ありがとうございます！確認しました。
クローズしちゃって大丈夫でしょうか？

**Comment by imajoriri** [comment]
@Uchino-recurrent 
ありがとうございます、大丈夫です！
Closeお願いします！

**Comment by UchinoHiroki1998** [comment]
@imajoriri 

これからも意見することあるかと思いますがよろしくお願いします！

**Comment by imajoriri** [comment]
ぜひぜひ、お待ちしております！
