### ISSUE TITLE
pull request の re-review を押すとerrorが出る

### ISSUE THREAD

**Issue by hashibadaiki** [tinp-lab/Mokuren-feedback#17]
### バグの内容

pull request の re-review を押すとerrorが出る
![Screen Shot 2022-06-28 at 9 08 58](https://user-images.githubusercontent.com/57456234/176059986-2879cef3-5549-42ba-b7e3-69834851fd0b.png)

### バージョン

`Mokuren for GitHub 2.0.4`

**Comment by imajoriri** [comment]
@hashibadaiki 

バグのご報告ありがとうございます！
スクリーンショットまで撮っていただき助かります。

確認し、修正しましたらこちらのIssueでご報告させていただきます。

**Comment by imajoriri** [comment]
@t4t5u0 
大変長らくお待たせいたしました！
最新のバージョン(2.1.2)で、こちら修正いたしました。
お手隙でご確認の方よろしくお願いします。
もし、反映されていそうでしたらこちらのIssueはCloseしちゃってください🙏


### Mokurenのアップデート方法

Chromeを再起動するか、以下の方法でお願いします。

1. デベロッパーモードON
2. 更新

で可能です！
**他のchrome拡張も更新されてしまうことに注意してください！**

<img width="1435" alt="スクリーンショット_2022-06-26_18_27_34" src="https://user-images.githubusercontent.com/30540418/175808080-ac071110-827f-44e8-b9a9-2ce34b91bebf.png">

**Comment by imajoriri** [comment]
@hashibadaiki 
大変長らくお待たせいたしました！
最新のバージョン(2.1.2)で、こちら修正いたしました。
お手隙でご確認の方よろしくお願いします。
もし、反映されていそうでしたらこちらのIssueはCloseしちゃってください🙏


### Mokurenのアップデート方法

Chromeを再起動するか、以下の方法でお願いします。

1. デベロッパーモードON
2. 更新

で可能です！
**他のchrome拡張も更新されてしまうことに注意してください！**

<img width="1435" alt="スクリーンショット_2022-06-26_18_27_34" src="https://user-images.githubusercontent.com/30540418/175808080-ac071110-827f-44e8-b9a9-2ce34b91bebf.png">

**Comment by hashibadaiki** [comment]
@imajoriri 
確認できました。ご対応ありがとうございますmm
