### ISSUE TITLE
Issueを開いた時にESCキーでも閉じれるようにしてほしい

### ISSUE THREAD

**Issue by maztak** [tinp-lab/Mokuren-feedback#18]
## 提案・要望
IssueやPRを開いた時に Cmd+Bで閉じれる機能をESCキーでも提供して欲しいです。もともとのIssue一覧部分のリンクでない部分をクリックして閉じるでもありがたいです。

## 背景
Cmd+Bがキー配置的に押しづらいのと、他アプリケーションでの標準的にESCキーだとすごく幸せになります。

## p.s.
imajoさんお疲れさまです笑
最近Github上で仕事をすることになり、Mokurenのよさがようやくわかりました笑。チームにも普及させていきたい‥。
余裕があれば実装いただいたり、何か背景があってCmd+Bにしてるのだればお手数ですがReject？してClonseしてくださいませm(_ _)m

**Comment by maztak** [comment]
既出のIssue見てなかった、、すみません。
こちらで提案され、すでに Cmd+B は実装されている状態みたいですね👀
https://github.com/tinp-lab/Mokuren-feedback/issues

**Comment by imajoriri** [comment]
@maztak 

わ、お久しぶりです！
要望ありがとうございます！

Cmd+B押しずらいのなるほどです...
esc、確かにめちゃくちゃ良いのですが、実はchrome拡張として使えるショートカットキーに制限がありまして🥲(cmdかAltを含まないといけないとか...)

もうちょい使いやすいショートカットキーを検討してみます！
あと、実はショートカットはユーザー自身でも変更可能でして、 こちらからも変更できます！
ぜひ試してみてください！
`chrome://extensions/shortcuts`

> 最近Github上で仕事をすることになり、Mokurenのよさがようやくわかりました笑。チームにも普及させていきたい‥。

めちゃくちゃ嬉しいです！
ぜひぜひ普及させてください！！

**Comment by maztak** [comment]
なるほど、そういう事情があるんですね‥！
このカスタマイズ、私もみてみます！Mokuren自体にもPRできそうなのがあったらしたいんですが、慣れも含めてだいぶ先になりそうです（笑）
ではこのIssueはクローズしてしまいますね！

**Comment by imajoriri** [comment]
ありがとうございます！！
気になったことがあったら、ばしばしIssueでもいいので教えてください！
