### ISSUE TITLE
Projectsを表示してほしい

### ISSUE THREAD

**Issue by t4t5u0** [tinp-lab/Mokuren-feedback#19]
## 提案・要望

![image](https://user-images.githubusercontent.com/48282855/176641686-0f79a833-2dac-4ffd-aa4a-bb178d390aed.png)

の欄にProjectsも表示してほしいです

## 背景

Projects Beta のために，Projectを指定したかったので

**Comment by imajoriri** [comment]
@t4t5u0 

機能改善の提案、ありがとうございます！
確かに、今Projectとアサインがない状況で…ご不便をおかけします🙏

こちら、実装可能か調査してみます。
状況が変わり次第、こちらのIssueで報告させていただきます！

**Comment by imajoriri** [comment]
@t4t5u0 
大変長らくお待たせいたしました！
最新のバージョン(2.1.2)で、こちら修正いたしました。
お手隙でご確認の方よろしくお願いします。
もし、反映されていそうでしたらこちらのIssueはCloseしちゃってください🙏


### Mokurenのアップデート方法

Chromeを再起動するか、以下の方法でお願いします。

1. デベロッパーモードON
2. 更新

で可能です！
**他のchrome拡張も更新されてしまうことに注意してください！**

<img width="1435" alt="スクリーンショット_2022-06-26_18_27_34" src="https://user-images.githubusercontent.com/30540418/175808080-ac071110-827f-44e8-b9a9-2ce34b91bebf.png">
