### ISSUE TITLE
Issuesページから移動したらIssueを閉じてほしい

### ISSUE THREAD

**Issue by t4t5u0** [tinp-lab/Mokuren-feedback#20]
## 提案・要望

Issuesページから移動したらIssueを閉じてほしいです．

## 背景

/issues から移動したらIssueの情報はあまり重要ではない気がします．例えば以下の画像で，続けてIssueを確認したい状況はあまりないように思えます．

![image](https://user-images.githubusercontent.com/48282855/176643049-2e2ee6cc-6edf-44a6-96bb-f45bac313394.png)

**Comment by imajoriri** [comment]
@t4t5u0 

こちらのIssueもありがとうございます！😊
すごく助かります！

確かに…画面遷移したらもう開いておく必要無さそうですね。
こちら次のリリースで改善します。
リリースされましたらこちらのIssueで報告させていただきます！

**Comment by imajoriri** [comment]
@t4t5u0 

お待たせしました！
他の画面へ遷移時にサイドバーを閉じるようにしました。
ぜひ、確認してみてください！
version2.0.6で動作します！
修正されていそうでしたらこちらのIssueをCloseしていただけると助かります！

自分でMokurenを使っていても、この改善は良かったと感じています。
ありがとうございます。

### Mokurenのアップデート方法

chrome拡張は自動で更新されますが、すぐにアップデートするには拡張一覧ページから

1. デベロッパーモードON
2. 更新

で可能です！
**他のchrome拡張も更新されてしまうことに注意してください！**

<img width="1435" alt="スクリーンショット_2022-06-26_18_27_34" src="https://user-images.githubusercontent.com/30540418/175808080-ac071110-827f-44e8-b9a9-2ce34b91bebf.png">

**Comment by t4t5u0** [comment]
よさそうです！対応ありがとうございました
