### ISSUE TITLE
Close sidebarのデフォルトショートカットキーを変更して欲しい

### ISSUE THREAD

**Issue by ryochike** [tinp-lab/Mokuren-feedback#21]
## 提案・要望
- デフォルトのサイドバーを閉じるショートカットキーをCmd + Bから変更して欲しい
<img width="708" alt="image" src="https://user-images.githubusercontent.com/45190770/177064418-031ad11a-75e0-4c4b-80d4-a9e8311389a8.png">

## 背景
デフォルトがCmd + Bになっている影響で、ブラウザ上で利用する全てのマークダウンエディタ（Slack、Notion、Githubなど）で**太字**のショートカットが利用できなくなった。

ブラウザの設定上からショートカット設定を変更することで治ったが、こちらの拡張機能の影響であることに気づくまで3日ほどかかった。

デフォルトで利用するショートカットキーは影響範囲の大きいショートカットキーにしないほうが良さそうです。（もしどこかにCmd + Bが利用できなくなるという注釈あったらすみません。）

**Comment by ryochike** [comment]
こちら、機能追加のissueで言及されているようですね。
突然Boldのショートカットキーが利用できなくなったため、かなり焦りました（しばらく別ブラウザを利用してました）。
現状はショートカットキーを変更することで対応できていますので、Closeしておきます。

**Comment by imajoriri** [comment]
@Ryochike 

Issueの起票ありがとうございます！
他と被るショートカットでご迷惑をおかけして、大変申し訳ありません！

こちら我々としても重大なバグとして捉え、次のリリースでデフォルトのショートカットキーを変更する予定です。
今後ともMokurenをよろしくお願いいたします。

**Comment by ryochike** [comment]
こちら重複するIssueとなってすみません！
非常に便利に利用させていただいています、今後も開発応援してます🙌

**Comment by imajoriri** [comment]
@Ryochike 

最新のバージョン2.0.6でデフォルトのショートカットキーを変更しました！
もう既にキーを変更されてると思うので、関係ないかもしれないですが、貴重な要望をいただいておりましたので報告させていただきました！
