### ISSUE TITLE
github.com/issues や, /pulls でも使用したい

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [tinp-lab/Mokuren-feedback#22]
いつも便利に利用させてもらっています.

## 提案・要望
+ https://github.com/issues や, https://github.com/pulls 直下からでもMokurenを使用できるようにして欲しいです.

以下の3つのURLからの使用を想定しています.
+ https://github.com/issues
+ https://github.com/issues/assigned
+ https://github.com/issues/mentioned
+ https://github.com/pulls
+ https://github.com/pulls/assigned
+ https://github.com/pulls/mentioned
+ https://github.com/pulls/review-requested

## 背景
私にアサインされたIssueを一覧で見るときに使用したいです.

---

よろしくお願い致します.

**Comment by imajoriri** [comment]
@peyang-Celeron 

いつもMokurenを利用いただきありがとうございます！
また、機能改善のご要望、とても助かります！

こちらのIssueでいただいた通り、`https://github.com/issues`などのページでもIssueにアクセス可能か調査し、機能追加させていただこうと思います。
リリースされ次第、こちらのIssueでご連絡します。よろしくお願いします。

**Comment by imajoriri** [comment]
@peyang-Celeron 

お世話になってます！
最新のバージョン(2.1.2)で、こちらご提案いただいていた `https://github.com/issues`のページでも使えるようにしました！
お手隙でご確認の方よろしくお願いします。
もし、反映されていそうでしたらこちらのIssueはCloseしちゃってください🙏


### Mokurenのアップデート方法

Chromeを再起動するか、以下の方法でお願いします。

1. デベロッパーモードON
2. 更新

で可能です！
**他のchrome拡張も更新されてしまうことに注意してください！**

<img width="1435" alt="スクリーンショット_2022-06-26_18_27_34" src="https://user-images.githubusercontent.com/30540418/175808080-ac071110-827f-44e8-b9a9-2ce34b91bebf.png">

**Comment by PeyaPeyaPeyang** [comment]
確認できました。 ありがとうございます！

![image](https://user-images.githubusercontent.com/42040068/182575317-a8275d78-fefb-41b6-bebb-65ef3c0a19bd.png)
