### ISSUE TITLE
Mokurenの画面を更新することができるようにしてほしい

### ISSUE THREAD

**Issue by rito528** [tinp-lab/Mokuren-feedback#24]
開発お疲れ様です。
いつも便利に使わせていただいております。

### Suggestions or requests
---
MokurenでPullRequestなどを開いた状態で、Mokuren画面の更新をすることができるようにして欲しいです。
ボタンでもいいですし、Web画面を更新したときに開いた状態で更新されるようになると嬉しいです。

### Background
---
PullRequestを開き、ブランチの更新がされたときに画面が更新されず、ブラウザ側で更新をするとMokurenの画面が閉じられてしまうので、開き直さずに画面を更新することができれば便利かなと思いました。

**Comment by imajoriri** [comment]
@rito528 さん

いつもMokurenをご利用いただきありがとうございます！
また、機能改善のご要望大変助かります。😊

確かに、自動更新されるわけでもないので毎回ブラウザリロード手間ですよね...(申し訳ございません！)
ご提案いただいた、サイドバー(Mokurenの画面)に更新ボタンを追加する等の対応を入れようか検討中です！


実装とストア申請で1,2週間はどうしてもかかってしまいます。
その間の応急処置的な感じですが、開いているPull requestをもう一度クリックすると更新かかりますので、その機能をお使いください！(わかりずらい挙動ですいません)

よろしくお願いいたします。

**Comment by rito528** [comment]
@imajoriri さん

返信ありがとうございます。
検討していただけると大変助かります！

> その間の応急処置的な感じですが、開いているPull requestをもう一度クリックすると更新かかりますので、その機能をお使いください！

了解しました。教えていただきありがとうございます。
とりあえず教えていただいた方法で利用しようと思います！

**Comment by imajoriri** [comment]
@rito528 

お世話になります！
最新のバージョン(2.1.3)で、リロードボタンを追加しました！
お手隙でご確認の方よろしくお願いします。
もし、反映されていそうでしたらこちらのIssueはCloseお願いします！

![スクリーンショット_2022-08-10_8_40_32](https://user-images.githubusercontent.com/30540418/183780047-7e16491e-165a-4c31-a7a8-2d8e18918762.png)



### Mokurenのアップデート方法

Chromeを再起動するか、以下の方法でお願いします。

1. デベロッパーモードON
2. 更新

で可能です！
**他のchrome拡張も更新されてしまうことに注意してください！**

<img width="1435" alt="スクリーンショット_2022-06-26_18_27_34" src="https://user-images.githubusercontent.com/30540418/175808080-ac071110-827f-44e8-b9a9-2ce34b91bebf.png">

**Comment by rito528** [comment]
確認できました！ありがとうございます！！！
