### ISSUE TITLE
IssuesやPull Requestsのタブを開くと他のページに移動できなくなる

### ISSUE THREAD

**Issue by Lucky3028** [tinp-lab/Mokuren-feedback#28]
いつもお世話になっております。
以下不具合を発見いたしましたので、ご連絡させていただきます。

### バグの内容
任意のGitHubレポジトリにおいて、IssuesやPull Requestsのタブを開くと、そこから他のタブやページに移動が一切できなくなる動作が発生しました。
「他のタブやページに移動が一切できなくなる」とは、他のタブやメニュー（サインアウトする、など）をクリックしても、一瞬その内容が映るだけで、すぐに開いていたIssuesまたはPullRequestsのタブに戻ってしまうということです。

以下切り分けを行いましたが、状況は改善しませんでした。

- キャッシュなしでのリロード
- キャッシュの削除
- サインインし直し
- ブラウザの再起動
- パソコンの再起動

以下切り分けを行ったところ、状況が改善しました。

- 他ブラウザを使用する
- Mokurenを無効にする

### バージョン

2.4.0

お忙しいところ大変恐縮ですが、以上ご確認のほどよろしくお願いいたします。

**Comment by imajoriri** [comment]
バグ起票ありがとうございます！
こちらでも再現できましたので、なるべく早く修正して再度、このIssueにてご連絡させていただきます！
@Lucky3028

**Comment by Lucky3028** [comment]
ご確認いただきありがとうございます。
修正していただけるとのことで承知いたしました。
よろしくお願いいたします。

**Comment by imajoriri** [comment]
@Lucky3028 
お世話になります。
こちらのバグ修正しましたので、バージョンを2.4.1に更新して試していただけると幸いです！

**Comment by Lucky3028** [comment]
@imajoriri 
お世話になっております。
ご連絡いただきありがとうございます。
v2.4.1にて、当該不具合が解消されていることを確認いたしました。
ご対応いただきありがとうございました。
