### ISSUE TITLE
Issueに紐づいているリポジトリ名がピンリストに欲しい

### ISSUE THREAD

**Issue by nekocodeX** [tinp-lab/Mokuren-feedback#3]
## 提案・要望

ピンリストのマイルストーンが表示される場所の先頭に `{Organization or User name}/{Repository name}` の表示を追加する

### イメージ (現状)
![image](https://user-images.githubusercontent.com/65624234/121631707-90fa9080-caba-11eb-8d60-9a61f06205c2.png)

### イメージ (リクエスト)
![image](https://user-images.githubusercontent.com/65624234/121631502-2ea19000-caba-11eb-8908-01342f37d9ca.png)

## 背景

1つのリポジトリでのみMokurenを利用する場合は困らないのですが、複数リポジトリで利用すると、どのリポジトリに紐づいたIssueなのかピンリストで分からない状態になっています。
ピンリストからIssueの詳細を開いても表示されないようなので、出来ましたら機能追加をお願いいたします。

### バージョン
- Google Chrome v91.0.4472.101
- Mokuren v1.0.4

**Comment by imajoriri** [comment]
@nekocodeX 

ご要望ありがとうございます。
こちらご提案いただいたように、以下のような表示で検討中です。
バージョンアップデートをしばらくお待ちください。
また、表示情報をなるべく少なくするために、ピンしているIssueのリポジトリが1つの場合はリポジトリ名を非表示にする対応をする予定です。

![🎉_Thanks_for_installing_Mokuren___🎉_·_Issue__1_·_tinp-lab_Mokuren-on-boarding](https://user-images.githubusercontent.com/30540418/121638840-99f15f00-cac6-11eb-93e7-4b486d9ca08f.png)

**Comment by nekocodeX** [comment]
Mokuren v1.0.5で実装されたようなので、こちらでクローズします。

ご対応いただきありがとうございました！
