### ISSUE TITLE
pr画面のConversationタブを開いている時にCommitログが常にみえたらうれしいかも

### ISSUE THREAD

**Issue by kasai-ryota** [tinp-lab/Mokuren-feedback#4]
## 提案・要望
pr画面のConversationタブを開いている時にCommitログが常にみえたらうれしいかもです

## 背景
prのレビュー指摘対応を行った時に下記のような感じで、コメントと一緒にxxで修正しましたと基本的につけるんですが、このコミットログのリンクを取ってくるために今はコミットログ用タブを追加で一つ開くようにしています。コミットログ用タブを開いていないときは、コミットログ用タブを開くために現在のConversationタブを基本的に一番上までスクロールしてCommitタブを押すというやり方が染み付いているのでそうやってるんですがスクロール位置はなるべく動かしたくないのでなんか解消できたら嬉しいです。

<img width="815" alt="スクリーンショット 2021-06-12 0 40 49" src="https://user-images.githubusercontent.com/35305920/121712599-e1074080-cb16-11eb-85e7-b5578a2af1c4.png">

あと自分のmacでのみ起こる現象なのかもしれませんがコミットログのリンクをコピーするボタンの反応が悪いことが多いので、コミットログのリンクをコピーするのがちょびっとストレスになることが多いです。
<img width="201" alt="スクリーンショット 2021-06-12 0 56 43" src="https://user-images.githubusercontent.com/35305920/121714773-2298eb00-cb19-11eb-9e5d-79e34c480bad.png">

**Comment by imajoriri** [comment]
@kasai-ryota 

ありがとうございます！
こちら開発メンバーで検討してみます。またいくつか質問することがあるかもしれないですが、そのときはよろしくお願いします！
