### ISSUE TITLE
サイドバーで開いた Issue の Description 欄のチェックボックスをチェック・アンチェックできるようにする

### ISSUE THREAD

**Issue by KosukeSaigusa** [tinp-lab/Mokuren-feedback#5]
## 提案・要望

テストユーザーとして、ありがたく使用させて頂いています！素敵なアプリケーションを開発して下さってありがとうございます🙇‍♂️

添付したスクショのように「サイドバーで開いた Issue の Description 欄のチェックボックスをチェック・アンチェックできるようにする」のはどうかという機能リクエストです。

![ZEN_開発プロジェクト](https://user-images.githubusercontent.com/13669049/121793603-acd97000-cc3b-11eb-9d04-40d8f923a328.png)

## 背景

GitHub Issue の Description 欄に Markdown チェックボックス付きの文章を書き、その Issue を完了させるための自身の進捗管理のために、終了し次第チェックを付けるようなことを個人的によくやります。

GitHub の Issue を通常の方法で開く時や、Projects のカンバンに登録されている Issue を表示させる時は、この Description 欄に書いた Markdown のチェックボックスは、Description の編集モードに入らなくても、そのチェックボックス部分をクリックすることで、チェック・アンチェックすることができます。

https://user-images.githubusercontent.com/13669049/121793693-a8fa1d80-cc3c-11eb-9030-27a66504f72d.mov

Mokuren でもこれができるといいなと思うときがあるので、ご検討よろしくお願いします🙏

**Comment by imajoriri** [comment]
@KosukeSaigusa 

こちらこそいつもありがとうございます！
また、機能リクエストありがとうございます！

こちら提案いただいたように、コメントないでもチェックボックスをチェック・アンチェックできるように実装したいと思います。
追加次第またコメントさせていただきたいと思います。
よろしくお願いいたします🙇‍♂️
