### ISSUE TITLE
ページの背景色が黒系統だとページ上部に戻るボタンが見づらい

### ISSUE THREAD

**Issue by roottool** [tinp-lab/Mokuren-feedback#7]
### バグの内容

背景色を黒系統に設定していると、詳細画面左下にあるページ上部に戻るボタンが見づらくなっています。

### 再現方法

1. アカウントの設定ページに遷移する
2. 左側のリストにある `Appearance` をクリックする
3. テーマを下記の3つの内の1つにする
    - Default dark
    - Dark dimmed
    - Dark high contrast

### スクリーンショット

![image](https://user-images.githubusercontent.com/11808736/125276135-d5dc4600-e34a-11eb-90e7-9c3f17289fea.png)

### バージョン
1.1.0

**Comment by imajoriri** [comment]
@roottool 

フィードバックありがとうございます！
こちらのバグをバージョン1.1.1で修正しました

もしお時間があれば試していただけると幸いです。

**Comment by roottool** [comment]
@imajoriri アップデートによって修正されているのを確認しました、対応ありがとうございます！
