### ISSUE TITLE
Github をサインアウト後に再度サインインすると Mokuren のローディングが終わらない

### ISSUE THREAD

**Issue by roottool** [tinp-lab/Mokuren-feedback#8]
### バグの内容

Mokuren を使用中のアカウントを一度サインアウトして再度サインインをすると、 ピン留めリストのローディングが終わらない

### 再現方法

1. Github アカウントをサインアウトする
2. サインアウトした Github アカウントに再度サインインする
3. Mokuren のピン留めリストを開く

一例ではありますがサインアウトを検知した場合は、 Mokuren をインストール後に最初に表示されるサインインボタンがあるページが表示されるとユーザーが対処出来ると思います。

### バージョン

1.1.2

**Comment by imajoriri** [comment]
@roottool いつもMokurenのご利用、またバグ報告ありがとうございます。
こちら次のアップデートで修正の予定です。少々お待ち下ください。
また何かありましたらこのissueにコメントさせていただきます

**Comment by imajoriri** [comment]
こちらバージョン1.1.3で、GitHubをサインアウトした後、**該当するブラウザのタブをリロードすると**Mokurenのログイン画面が開くよう修正いたしました。
@roottool

**Comment by roottool** [comment]
@imajoriri ログイン画面の表示を確認しました！修正ありがとうございます！🙇
